// <auto-generated />
using System;
using LoiOpdracht.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoiOpdracht.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200724174422_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("LoiOpdracht.Models.Coach", b =>
                {
                    b.Property<int>("CoachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .HasColumnType("TEXT");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CoachId");

                    b.ToTable("Coach");
                });

            modelBuilder.Entity("LoiOpdracht.Models.Speler", b =>
                {
                    b.Property<int>("SpelerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktief")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .HasColumnType("TEXT");

                    b.Property<string>("Straatnaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Woonplaats")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SpelerId");

                    b.ToTable("Speler");
                });

            modelBuilder.Entity("LoiOpdracht.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CoachId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoortSport")
                        .HasColumnType("TEXT")
                        .HasMaxLength(30);

                    b.Property<int?>("Speler2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpelerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamNaam")
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId");

                    b.HasIndex("CoachId");

                    b.HasIndex("Speler2Id");

                    b.HasIndex("SpelerId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("LoiOpdracht.Models.Team", b =>
                {
                    b.HasOne("LoiOpdracht.Models.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId");

                    b.HasOne("LoiOpdracht.Models.Speler", "Speler2")
                        .WithMany()
                        .HasForeignKey("Speler2Id");

                    b.HasOne("LoiOpdracht.Models.Speler", "Speler1")
                        .WithMany()
                        .HasForeignKey("SpelerId");
                });
#pragma warning restore 612, 618
        }
    }
}
